# Generated by Django 2.0.3 on 2018-04-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('long_url', models.CharField(max_length=100, null=True)),
                ('short_url', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
