# Generated by Django 2.0.3 on 2018-04-03 10:37

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.IntegerField(default=api.models.random_number)),
                ('long_url', models.CharField(max_length=100)),
                ('short_url', models.CharField(blank=True, max_length=30)),
            ],
        ),
    ]
