# Generated by Django 2.0.3 on 2018-04-03 11:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='unique_id',
            field=models.CharField(default=api.models.random_number, max_length=7),
        ),
    ]
