# Generated by Django 2.0.3 on 2018-04-03 11:08

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180403_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='unique_id',
            field=models.IntegerField(default=api.models.random_number),
        ),
    ]
