# Generated by Django 2.0.3 on 2018-04-03 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180403_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
